apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath-01
spec:
  storageClassName: standard
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/abhi/tmp/pv-host
