apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-localhost-01
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
  volumeName: pv-hostpath-01 
