apiVersion: v1
kind: Pod
metadata:
  name: my-bb
spec:
  containers:
  - command: ["/bin/sh"]
    args:
    - -c
    - >-
        shuf -i 1-100 -n 1 > /output/rand
        && tail -f /dev/null
    image: busybox
    name: my-bb
    volumeMounts:
    - name: data
      mountPath: /output
  restartPolicy: Never
  volumes:
  - name: data
    hostPath:
      path: /home/abhi/tech/kubernetes/study
      type: Directory
