apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: my-nginx
  name: my-nginx-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      containers:
      - image: nginx
        name: my-nginx-cnt
