apiVersion: v1
kind: Pod
metadata:
  labels:
    run: my-busybox
  name: my-busybox
spec:
  containers:
  - image: busybox
    name: my-busybox
    env:
      - name: MY_ENV_KEY_1
        value: "my env val 1"
      - name: MY_ENV_KEY_2
        value: "my emv val 2"
#      - name: MY_CONF_KEY_1
#        valueFrom:
#          configMapKeyRef:
#            name: my-bb-cm  
#            key: MY_CM_KEY_1
#      - name: MY_CONF_KEY_2
#        valueFrom:
#          configMapKeyRef:
#            name: my-bb-cm  
#            key: MY_CM_KEY_2

    command: ["/bin/sh"]
    args:
      - -c
      - >-
          env &&
          tail -f /dev/null
