apiVersion: v1
kind: Pod
metadata:
  name: dummy-acc-app
  namespace: accounting
spec:
  containers:
  - image: alpine_plus
    name: dummy-acc-app
    imagePullPolicy: Never
    command: ["/bin/sh"]
    args:
      - -c
      - >-
        echo ===== Dummy App on Alipne with cUrl ====
        && tail -f /dev/null
  restartPolicy: Never
  serviceAccountName: acc-app-sa
