apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acc-pods
  namespace: accounting
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
