apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acc-alice-rb
  namespace: accounting
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acc-pods
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: Alice Smith
